### ISSUE TITLE
3D buttons not working on IE10

### ISSUE THREAD

**Issue by kbariotis** [codrops/CreativeButtons#1]
Even this http://css-tricks.com/pseudo-element-animationstransitions-bug-fixed-in-webkit/ would not work.

**Comment by cdawsonhall** [comment]
selectivizr.js might be a solution... helps with alot of psudo elements in IE, and it's only 5k... I'd be interested in checking that out it you'd like... http://selectivizr.com/

**Comment by crnacura** [comment]
This is an issue with IE10 itself: it simply does not support the crucial "preserve-3d" transform-style:

"At this time, Internet Explorer 10 does not support the preserve-3d keyword. You can work around this by manually applying the parent element's transform to each of the child elements in addition to the child element's normal transform." 
http://msdn.microsoft.com/en-gb/library/ie/hh673529%28v=vs.85%29.aspx#the_ms_transform_style_property

The :before and :after pseudo elements work from IE8 (partial) on but anyway, 3D transforms are just supported from IE10 on (kind of, as we can see).
